title: Program Playbook Template
description: Program Playbook Template
theme: just-the-docs

url: https://translatorswb.github.io/program-playbook

aux_links: # remove if you don't want this link to appear on your pages
  Template Repository: https://github.com/translatorswb/program-playbook
